<?php
class Controller_Chat extends Controller
{
    function __construct()
    {
        $this->model = new Model_Chat();
        $this->view = new View();
    }

    function action_index()
    {
        parent::action_index(); // TODO: Change the autogenerated stub
        $data = $this->model->get_data();
        $this->view->generate('chat_view.php', 'template_view.php', $data);
    }
}